### ISSUE TITLE
Image path does not match the cropped dataset

### ISSUE THREAD

**Issue by ganlumomo** [avaapm/SGADA#2]
Hi,

Thank you for the great work and opensource code. I encountered a problem when trying to replicate the results.
It seems that the image path in test_wconf_wdomain_weights.txt does not match the cropped dataset, therefore, the train data loader could not find the correct image path.
Could you please give a hint how to solve the problem? Thank you so much!

**Comment by avaapm** [comment]
Hi Lu,

Thank you for your interest in our work. I am sorry for the late reply.

If you run `prepare_dataset.py` and perform warm-up stage using ADDA repo on cropped dataset, I think it is better to generate pseudo label files instead of using the files in the repo. Have you tried to generate pseudo label files?

**Comment by ganlumomo** [comment]
Hi, I am able to generate pseudo labels based on ADDA repo and the cropped dataset. Thank you so much! I will close this.
